### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureServer#1]
- [x]  change URL : `http://glp.mgravey.com/GeoPressure/v1/map.py`
- [x]  create assert/check of all inputs varible: `W,E,S,N, scale, time, pressure, label`
- [x]  Error message if pressure, time and lable don't have the same size.
- [x] create log with id (Return link to to this repo issue in the api if error).
- [x] Check for time after available date and return error/warning message in case after or before available data
- [x]  switch between ERA5-land or surface level
- [ ] #5
- [x] Resolve label in python (rather than gee)
- [ ] #3
- [x] change task_id and messa_... to taskID etc... @mgravey  
- [x] #4
- [x]  confirm documentation for `margin` in map
